"""Add is_pinned and is_archived to Participant

Revision ID: 0b8586569e92
Revises: c9a612bb075e
Create Date: 2025-08-29 15:07:33.244370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8586569e92'
down_revision = 'c9a612bb075e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_group', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('group_photo_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('invite_code', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('is_invite_link_enabled', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_conversations_invite_code', ['invite_code'])

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_column('is_archived')
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('role')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_conversations_invite_code', type_='unique')
        batch_op.drop_column('is_invite_link_enabled')
        batch_op.drop_column('invite_code')
        batch_op.drop_column('group_photo_path')
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('is_group')

    # ### end Alembic commands ###
